sketch-hq/sketch-document

- schema/enums/fill-type.schema.yaml
- schema/layers/symbol-master.schema.yaml
- schema/objects/color-asset.schema.yaml
- schema/objects/color-controls.schema.yaml
- schema/objects/gradient-asset.schema.yaml
- schema/objects/gradient.schema.yaml
- schema/objects/override-name.schema.yaml
- schema/objects/override-property.schema.yaml
- schema/objects/override-value.schema.yaml
- schema/objects/paragraph-style.schema.yaml
- schema/utils/point-string.schema.yaml
closes #40, closes #35, closes #34, closes #33, closes #32, closes #31, closes #30, closes #29
> fix: correctness fixes

- scripts/assemble.mjs
Refs https://github.com/sketch-hq/BCTools/issues/487
Previously references in the schemas used ids,
```
{
properties: {
id: { $ref: "#Uuid" }
}
}
```
Unfortunately this isn't [currently supported](https://github.com/Julian/jsonschema/pull/371) by the jsonschema Python lib, despite it being a valid approach and part of the JSON Schema spec. 
We can instead use JSON Pointers as refs, which work just as well as ids. So reference usage after this change looks like:
```
{
properties: {
id: { $ref: "#/definitions/Uuid" }
}
}
```
The functionality of the schemas remains otherwise identical.
> feat: change ref format to a pointer into the definitions obj

- schema/enums/strikethrough-style.schema.yaml
> fix: fix strikethrough-style title

- schema/layers/shape-group.schema.yaml
> fix: remove sharedStyleID from shape-group schema

- schema/objects/override-value.schema.yaml
Refs https://github.com/sketch-hq/sketch-file-format-ts/issues/9
> fix: override values can also be image-data-refs

- .changeset/five-kiwis-cheat.md
- schema/objects/embedded-font-ref.schema.yaml
Refs https://github.com/sketch-hq/Sketch/issues/28793
> feat: add embedded prop to font ref schema

- schema/enums/inferred-layout-axis.schema.yaml
> fix: layout axis schema

- .changeset/fifty-turtles-arrive.md
- schema/abstract-document.schema.yaml
- schema/meta.schema.yaml
Refs https://github.com/sketch-hq/Sketch/issues/29436
> feat: agreedToFontEmbedding prop

- .changeset/rare-pumas-burn.md
- schema/file-format.schema.yaml
- schema/objects/assistants-workspace.schema.yaml
- schema/workspace.schema.yaml
> feat: workspaces

- .changeset/real-pianos-unite.md
- schema/abstract-document.schema.yaml
- schema/objects/embedded-font-ref.schema.yaml
- schema/objects/font-data-ref.schema.yaml
- schema/objects/font-ref.schema.yaml
Refs https://github.com/sketch-hq/Sketch/issues/29749
> fix: embedded font schemas

- .changeset/hungry-masks-hunt.md
- schema/abstract-document.schema.yaml
- schema/meta.schema.yaml
- schema/objects/document-state.schema.yaml
> feat: document-state

- .changeset/tidy-berries-fetch.md
- schema/enums/bundle-id.schema.yaml
> Add missing bundle identifiers for feature preview variant

- .changeset/gold-plants-punch.md
- schema/layers/symbol-master.schema.yaml
> Remove changeIdentifier from symbol master

- .changeset/neat-forks-give.md
- .changeset/odd-walls-sell.md
- schema/layers/abstract-group.schema.yaml
- schema/layers/abstract-root-layer.schema.yaml
- schema/layers/artboard.schema.yaml
- schema/layers/page.schema.yaml
- schema/layers/symbol-master.schema.yaml
- Resolves #129
- Resolves #19
> Inherit from artboard

- .changeset/config.json
- .github/workflows/release.yml
- README.md
- schema/layers/symbol-instance.schema.yaml
- schema/objects/override-property.schema.yaml
Resolves #131
@jedrichards not sure if to merge into `master` first – which will break `changeset` temporarily or the other way round, or create a copy of `master` and merge there 🤔
> Change name of default branch to main

- .changeset/fair-pumas-decide.md
- schema/meta.schema.yaml
Resolve #137, include `coeditCompatibilityVersion`
> Bump document version

- .github/workflows/release.yml
Use bot account for versioning pull requests.
> Change secret used as `GITHUB_TOKEN`

- .changeset/sweet-buses-develop.md
- packages/file-format-ts/.gitignore
- packages/file-format-ts/README.md
- packages/file-format-ts/index.ts
- packages/file-format-ts/package.json
- packages/file-format-ts/scripts/generate.ts
- packages/file-format/src/index.ts
- packages/file-format/tsconfig.json
> Use latest schema only

- .changeset/five-dancers-pay.md
- packages/file-format/schema/layers/abstract-root-layer.schema.yaml
> Remove includeInCloudUpload attribute

- .changeset/early-forks-change.md
- packages/file-format/schema/layers/artboard.schema.yaml
See https://github.com/sketch-hq/Sketch/issues/35602
> Add didManuallyDisableResizingContent property

- .changeset/hungry-avocados-love.md
- .changeset/shy-files-march.md
- packages/file-format/schema/enums/export-format-naming-scheme.schema.yaml
Rename the description for the existing prefix.
Add a new enum value for the prefix called _Primary prefix_
> Prefix export format change

- .changeset/chilled-ads-deny.md
- packages/file-format/schema/meta.schema.yaml
Update schema to match a document version bump occurred in the Mac app (#40495).
> Bump Sketch document version

- .changeset/chilled-ads-deny.md
- .changeset/few-years-worry.md
- .changeset/pre.json
- .github/workflows/release.yml
- packages/file-format-ts/CHANGELOG.md
- packages/file-format-ts/package.json
- packages/file-format/CHANGELOG.md
- packages/file-format/package.json
- packages/file-format/schema/meta.schema.yaml
- packages/file/CHANGELOG.md
- packages/file/package.json
> Pre-release
